version: "3.8"

services:
  postgres_impiricus:
    image: postgres:16
    container_name: infra_postgres_impiricus
    restart: always
    environment:
      POSTGRES_USER: impiricus
      POSTGRES_PASSWORD: impiricus
      POSTGRES_DB: projeto_impiricus
    ports:
      - "5434:5432"
    volumes:
      - impiricus-pgdata:/var/lib/postgresql/data

  postgres_mlinsight:
    image: postgres:16
    container_name: infra_postgres_mlinsight
    restart: always
    environment:
      POSTGRES_USER: mlinsight
      POSTGRES_PASSWORD: mlinsight
      POSTGRES_DB: mlinsight
    ports:
      - "5532:5432"
    volumes:
      - mlinsight-pgdata:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    container_name: infra_prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: infra_grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  grafana-storage:
  impiricus-pgdata:
  mlinsight-pgdata:
