global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['infra_prometheus:9090']

  - job_name: 'microservice-core'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8080']  # microservi√ßo rodando local

  - job_name: 'api-collector'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8081']  # projeto API rodando local

  - job_name: 'robo-binance'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'host.docker.internal:8082' ] # Localhost enquanto desenvolve
    relabel_configs:
      - target_label: application
        replacement: robo-binance
      - target_label: environment
        replacement: development